### ISSUE TITLE
Add citation metadata

### ISSUE THREAD

**Issue by sdruskat** [mr-c/shouldacite#18]
Care to make *shouldacite* citable and let users know how to cite it ;-)?

**Comment by mr-c** [comment]
@louisepb @dimazest @izaromanowska Can you share your ORCIDs?

**Comment by mr-c** [comment]
Fixed in https://github.com/mr-c/shouldacite/commit/d5e169d5855804add9c6d611dc97f1f74f719e82, thank you @sdruskat !
